### ISSUE TITLE
http-vhost.conf Question

### ISSUE THREAD

**Issue by nielsnuebel** [renekreijveld/macOS-Local-Development-Setup#3]
```
<Virtualhost *:80>
    ServerName niels-nuebel.dev
    DocumentRoot /Users/niels/Development/Sites/niels-nuebel/dist/public
</Virtualhost>
```

how can i do this?

**Comment by renekreijveld** [comment]
Hi Niels, I'm not sure what you're trying to do. Do you want to have a local domain niels-nuebel.dev that points to /Users/niels/Development/Sites/niels-nuebel/dist/public ?
That is not possible because of this rule in httpd-vhosts.conf:

```
<Virtualhost *:80>
    VirtualDocumentRoot "/Users/your_user/Development/Sites/%1"
    ServerAlias *.dev
    UseCanonicalName Off
</Virtualhost>
```
I would suggest setting it up under a different domain name:

```
<VirtualHost *:80>
    ServerName niels-nuebel.test
    DocumentRoot "/Users/niels/Development/Sites/niels-nuebel/dist/public"
</VirtualHost>
```

Downside to this is that you have to add niels-nuebel.test to your hosts file pointing to 127.0.0.1.

**Comment by renekreijveld** [comment]
You could also have local .test domains automatically resolve to 127.0.0.1.
This can be done as follows. First add it to dnsmasq:

```
echo 'address=/.test/127.0.0.1' >> /usr/local/etc/dnsmasq.conf
```

Then restart dnsmasq:

```
sudo brew services restart dnsmasq
```
Than create a resolver for .test domains:

```
sudo bash -c 'echo "nameserver 127.0.0.1" > /etc/resolver/test'
```

Then any local .test domain resolves:
```
$ ping thisdoesnotexist.test
PING thisdoesnotexist.test (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.048 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.133 ms
64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.118 ms
```

**Comment by nielsnuebel** [comment]
@renekreijveld thanks, after i add .test to dnsmasq it's work like a charme
